// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
pub type Pair = demo::test::types::Pair;
pub type Color = demo::test::types::Color;
pub type Maybe = demo::test::types::Maybe;
pub type Perms = demo::test::types::Perms;
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_add_cabi<T: Guest>(arg0: i32, arg1: i32) -> i32 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let result0 = T::add(arg0 as u32, arg1 as u32);
    _rt::as_i32(result0)
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_sub_cabi<T: Guest>(arg0: i32, arg1: i32) -> i32 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let result0 = T::sub(arg0, arg1);
    _rt::as_i32(result0)
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_mul_f_cabi<T: Guest>(arg0: f32, arg1: f32) -> f32 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let result0 = T::mul_f(arg0, arg1);
    _rt::as_f32(result0)
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_div_d_cabi<T: Guest>(arg0: f64, arg1: f64) -> f64 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let result0 = T::div_d(arg0, arg1);
    _rt::as_f64(result0)
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_greet_cabi<T: Guest>(arg0: *mut u8, arg1: usize) -> *mut u8 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let len0 = arg1;
    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
    let result1 = T::greet(_rt::string_lift(bytes0));
    let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
    let vec3 = (result1.into_bytes()).into_boxed_slice();
    let ptr3 = vec3.as_ptr().cast::<u8>();
    let len3 = vec3.len();
    ::core::mem::forget(vec3);
    *ptr2.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len3;
    *ptr2.add(0).cast::<*mut u8>() = ptr3.cast_mut();
    ptr2
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_greet<T: Guest>(arg0: *mut u8) {
    let l0 = *arg0.add(0).cast::<*mut u8>();
    let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
    _rt::cabi_dealloc(l0, l1, 1);
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_sum_list_cabi<T: Guest>(arg0: *mut u8, arg1: usize) -> i32 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let len0 = arg1;
    let result1 = T::sum_list(_rt::Vec::from_raw_parts(arg0.cast(), len0, len0));
    _rt::as_i32(result1)
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_double_list_cabi<T: Guest>(arg0: *mut u8, arg1: usize) -> *mut u8 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let len0 = arg1;
    let result1 = T::double_list(_rt::Vec::from_raw_parts(arg0.cast(), len0, len0));
    let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
    let vec3 = (result1).into_boxed_slice();
    let ptr3 = vec3.as_ptr().cast::<u8>();
    let len3 = vec3.len();
    ::core::mem::forget(vec3);
    *ptr2.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len3;
    *ptr2.add(0).cast::<*mut u8>() = ptr3.cast_mut();
    ptr2
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_double_list<T: Guest>(arg0: *mut u8) {
    let l0 = *arg0.add(0).cast::<*mut u8>();
    let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
    let base2 = l0;
    let len2 = l1;
    _rt::cabi_dealloc(base2, len2 * 4, 4);
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_make_pair_cabi<T: Guest>(arg0: i32, arg1: i32) -> *mut u8 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let result0 = T::make_pair(arg0 as u32, arg1 as u32);
    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
    let demo::test::types::Pair { x: x2, y: y2 } = result0;
    *ptr1.add(0).cast::<i32>() = _rt::as_i32(x2);
    *ptr1.add(4).cast::<i32>() = _rt::as_i32(y2);
    ptr1
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_swap_pair_cabi<T: Guest>(arg0: i32, arg1: i32) -> *mut u8 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let result0 = T::swap_pair(demo::test::types::Pair {
        x: arg0 as u32,
        y: arg1 as u32,
    });
    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
    let demo::test::types::Pair { x: x2, y: y2 } = result0;
    *ptr1.add(0).cast::<i32>() = _rt::as_i32(x2);
    *ptr1.add(4).cast::<i32>() = _rt::as_i32(y2);
    ptr1
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_try_get_cabi<T: Guest>(arg0: i32) -> *mut u8 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let result0 = T::try_get(_rt::bool_lift(arg0 as u8));
    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
    match result0 {
        Ok(e) => {
            *ptr1.add(0).cast::<u8>() = (0i32) as u8;
            *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<i32>() = _rt::as_i32(
                e,
            );
        }
        Err(e) => {
            *ptr1.add(0).cast::<u8>() = (1i32) as u8;
            let vec2 = (e.into_bytes()).into_boxed_slice();
            let ptr2 = vec2.as_ptr().cast::<u8>();
            let len2 = vec2.len();
            ::core::mem::forget(vec2);
            *ptr1.add(2 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len2;
            *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr2
                .cast_mut();
        }
    };
    ptr1
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_try_get<T: Guest>(arg0: *mut u8) {
    let l0 = i32::from(*arg0.add(0).cast::<u8>());
    match l0 {
        0 => {}
        _ => {
            let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
            let l2 = *arg0.add(2 * ::core::mem::size_of::<*const u8>()).cast::<usize>();
            _rt::cabi_dealloc(l1, l2, 1);
        }
    }
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_pick_cabi<T: Guest>(arg0: i32, arg1: i32) -> *mut u8 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let result0 = T::pick(demo::test::types::Color::_lift(arg0 as u8), arg1 as u32);
    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
    match result0 {
        Some(e) => {
            *ptr1.add(0).cast::<u8>() = (1i32) as u8;
            *ptr1.add(4).cast::<i32>() = _rt::as_i32(e);
        }
        None => {
            *ptr1.add(0).cast::<u8>() = (0i32) as u8;
        }
    };
    ptr1
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_echo_maybe_cabi<T: Guest>(arg0: i32, arg1: i32) -> *mut u8 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    use demo::test::types::Maybe as V0;
    let v0 = match arg0 {
        0 => V0::None,
        n => {
            debug_assert_eq!(n, 1, "invalid enum discriminant");
            let e0 = arg1 as u32;
            V0::Some(e0)
        }
    };
    let result1 = T::echo_maybe(v0);
    let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
    use demo::test::types::Maybe as V3;
    match result1 {
        V3::None => {
            *ptr2.add(0).cast::<u8>() = (0i32) as u8;
        }
        V3::Some(e) => {
            *ptr2.add(0).cast::<u8>() = (1i32) as u8;
            *ptr2.add(4).cast::<i32>() = _rt::as_i32(e);
        }
    }
    ptr2
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_count_flags_cabi<T: Guest>(arg0: i32) -> i32 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let result0 = T::count_flags(
        demo::test::types::Perms::empty()
            | demo::test::types::Perms::from_bits_retain(((arg0 as u8) << 0) as _),
    );
    _rt::as_i32(result0)
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_not_bool_cabi<T: Guest>(arg0: i32) -> i32 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let result0 = T::not_bool(_rt::bool_lift(arg0 as u8));
    match result0 {
        true => 1,
        false => 0,
    }
}
pub trait Guest {
    fn add(a: u32, b: u32) -> u32;
    fn sub(a: i32, b: i32) -> i32;
    fn mul_f(a: f32, b: f32) -> f32;
    fn div_d(a: f64, b: f64) -> f64;
    fn greet(name: _rt::String) -> _rt::String;
    fn sum_list(xs: _rt::Vec<u32>) -> u32;
    fn double_list(xs: _rt::Vec<u32>) -> _rt::Vec<u32>;
    fn make_pair(a: u32, b: u32) -> Pair;
    fn swap_pair(p: Pair) -> Pair;
    fn try_get(flag: bool) -> Result<u32, _rt::String>;
    fn pick(choice: Color, val: u32) -> Option<u32>;
    fn echo_maybe(v: Maybe) -> Maybe;
    fn count_flags(f: Perms) -> u32;
    fn not_bool(b: bool) -> bool;
}
#[doc(hidden)]
macro_rules! __export_world_demo_cabi {
    ($ty:ident with_types_in $($path_to_types:tt)*) => {
        const _ : () = { #[unsafe (export_name = "add")] unsafe extern "C" fn
        export_add(arg0 : i32, arg1 : i32,) -> i32 { unsafe { $($path_to_types)*::
        _export_add_cabi::<$ty > (arg0, arg1) } } #[unsafe (export_name = "sub")] unsafe
        extern "C" fn export_sub(arg0 : i32, arg1 : i32,) -> i32 { unsafe {
        $($path_to_types)*:: _export_sub_cabi::<$ty > (arg0, arg1) } } #[unsafe
        (export_name = "mul-f")] unsafe extern "C" fn export_mul_f(arg0 : f32, arg1 :
        f32,) -> f32 { unsafe { $($path_to_types)*:: _export_mul_f_cabi::<$ty > (arg0,
        arg1) } } #[unsafe (export_name = "div-d")] unsafe extern "C" fn
        export_div_d(arg0 : f64, arg1 : f64,) -> f64 { unsafe { $($path_to_types)*::
        _export_div_d_cabi::<$ty > (arg0, arg1) } } #[unsafe (export_name = "greet")]
        unsafe extern "C" fn export_greet(arg0 : * mut u8, arg1 : usize,) -> * mut u8 {
        unsafe { $($path_to_types)*:: _export_greet_cabi::<$ty > (arg0, arg1) } }
        #[unsafe (export_name = "cabi_post_greet")] unsafe extern "C" fn
        _post_return_greet(arg0 : * mut u8,) { unsafe { $($path_to_types)*::
        __post_return_greet::<$ty > (arg0) } } #[unsafe (export_name = "sum-list")]
        unsafe extern "C" fn export_sum_list(arg0 : * mut u8, arg1 : usize,) -> i32 {
        unsafe { $($path_to_types)*:: _export_sum_list_cabi::<$ty > (arg0, arg1) } }
        #[unsafe (export_name = "double-list")] unsafe extern "C" fn
        export_double_list(arg0 : * mut u8, arg1 : usize,) -> * mut u8 { unsafe {
        $($path_to_types)*:: _export_double_list_cabi::<$ty > (arg0, arg1) } } #[unsafe
        (export_name = "cabi_post_double-list")] unsafe extern "C" fn
        _post_return_double_list(arg0 : * mut u8,) { unsafe { $($path_to_types)*::
        __post_return_double_list::<$ty > (arg0) } } #[unsafe (export_name =
        "make-pair")] unsafe extern "C" fn export_make_pair(arg0 : i32, arg1 : i32,) -> *
        mut u8 { unsafe { $($path_to_types)*:: _export_make_pair_cabi::<$ty > (arg0,
        arg1) } } #[unsafe (export_name = "swap-pair")] unsafe extern "C" fn
        export_swap_pair(arg0 : i32, arg1 : i32,) -> * mut u8 { unsafe {
        $($path_to_types)*:: _export_swap_pair_cabi::<$ty > (arg0, arg1) } } #[unsafe
        (export_name = "try-get")] unsafe extern "C" fn export_try_get(arg0 : i32,) -> *
        mut u8 { unsafe { $($path_to_types)*:: _export_try_get_cabi::<$ty > (arg0) } }
        #[unsafe (export_name = "cabi_post_try-get")] unsafe extern "C" fn
        _post_return_try_get(arg0 : * mut u8,) { unsafe { $($path_to_types)*::
        __post_return_try_get::<$ty > (arg0) } } #[unsafe (export_name = "pick")] unsafe
        extern "C" fn export_pick(arg0 : i32, arg1 : i32,) -> * mut u8 { unsafe {
        $($path_to_types)*:: _export_pick_cabi::<$ty > (arg0, arg1) } } #[unsafe
        (export_name = "echo-maybe")] unsafe extern "C" fn export_echo_maybe(arg0 : i32,
        arg1 : i32,) -> * mut u8 { unsafe { $($path_to_types)*::
        _export_echo_maybe_cabi::<$ty > (arg0, arg1) } } #[unsafe (export_name =
        "count-flags")] unsafe extern "C" fn export_count_flags(arg0 : i32,) -> i32 {
        unsafe { $($path_to_types)*:: _export_count_flags_cabi::<$ty > (arg0) } }
        #[unsafe (export_name = "not-bool")] unsafe extern "C" fn export_not_bool(arg0 :
        i32,) -> i32 { unsafe { $($path_to_types)*:: _export_not_bool_cabi::<$ty > (arg0)
        } } };
    };
}
#[doc(hidden)]
pub(crate) use __export_world_demo_cabi;
#[cfg_attr(target_pointer_width = "64", repr(align(8)))]
#[cfg_attr(target_pointer_width = "32", repr(align(4)))]
struct _RetArea([::core::mem::MaybeUninit<u8>; 3 * ::core::mem::size_of::<*const u8>()]);
static mut _RET_AREA: _RetArea = _RetArea(
    [::core::mem::MaybeUninit::uninit(); 3 * ::core::mem::size_of::<*const u8>()],
);
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod demo {
    pub mod test {
        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod types {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            #[repr(C)]
            #[derive(Clone, Copy)]
            pub struct Pair {
                pub x: u32,
                pub y: u32,
            }
            impl ::core::fmt::Debug for Pair {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("Pair")
                        .field("x", &self.x)
                        .field("y", &self.y)
                        .finish()
                }
            }
            #[repr(u8)]
            #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
            pub enum Color {
                Red,
                Green,
                Blue,
            }
            impl ::core::fmt::Debug for Color {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    match self {
                        Color::Red => f.debug_tuple("Color::Red").finish(),
                        Color::Green => f.debug_tuple("Color::Green").finish(),
                        Color::Blue => f.debug_tuple("Color::Blue").finish(),
                    }
                }
            }
            impl Color {
                #[doc(hidden)]
                pub unsafe fn _lift(val: u8) -> Color {
                    if !cfg!(debug_assertions) {
                        return ::core::mem::transmute(val);
                    }
                    match val {
                        0 => Color::Red,
                        1 => Color::Green,
                        2 => Color::Blue,
                        _ => panic!("invalid enum discriminant"),
                    }
                }
            }
            #[derive(Clone, Copy)]
            pub enum Maybe {
                None,
                Some(u32),
            }
            impl ::core::fmt::Debug for Maybe {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    match self {
                        Maybe::None => f.debug_tuple("Maybe::None").finish(),
                        Maybe::Some(e) => f.debug_tuple("Maybe::Some").field(e).finish(),
                    }
                }
            }
            wit_bindgen_rt::bitflags::bitflags! {
                #[derive(PartialEq, Eq, PartialOrd, Ord, Hash, Debug, Clone, Copy)] pub
                struct Perms : u8 { const READ = 1 << 0; const WRITE = 1 << 1; const EXEC
                = 1 << 2; }
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub fn as_i32<T: AsI32>(t: T) -> i32 {
        t.as_i32()
    }
    pub trait AsI32 {
        fn as_i32(self) -> i32;
    }
    impl<'a, T: Copy + AsI32> AsI32 for &'a T {
        fn as_i32(self) -> i32 {
            (*self).as_i32()
        }
    }
    impl AsI32 for i32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for char {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for usize {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    pub fn as_f32<T: AsF32>(t: T) -> f32 {
        t.as_f32()
    }
    pub trait AsF32 {
        fn as_f32(self) -> f32;
    }
    impl<'a, T: Copy + AsF32> AsF32 for &'a T {
        fn as_f32(self) -> f32 {
            (*self).as_f32()
        }
    }
    impl AsF32 for f32 {
        #[inline]
        fn as_f32(self) -> f32 {
            self as f32
        }
    }
    pub fn as_f64<T: AsF64>(t: T) -> f64 {
        t.as_f64()
    }
    pub trait AsF64 {
        fn as_f64(self) -> f64;
    }
    impl<'a, T: Copy + AsF64> AsF64 for &'a T {
        fn as_f64(self) -> f64 {
            (*self).as_f64()
        }
    }
    impl AsF64 for f64 {
        #[inline]
        fn as_f64(self) -> f64 {
            self as f64
        }
    }
    pub use alloc_crate::vec::Vec;
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            String::from_utf8_unchecked(bytes)
        }
    }
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr, layout);
    }
    pub use alloc_crate::string::String;
    pub unsafe fn bool_lift(val: u8) -> bool {
        if cfg!(debug_assertions) {
            match val {
                0 => false,
                1 => true,
                _ => panic!("invalid bool discriminant"),
            }
        } else {
            val != 0
        }
    }
    extern crate alloc as alloc_crate;
    pub use alloc_crate::alloc;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_demo_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*:: __export_world_demo_cabi!($ty with_types_in
        $($path_to_types_root)*);
    };
}
#[doc(inline)]
pub(crate) use __export_demo_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:demo:test:demo:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 685] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xb2\x04\x01A\x02\x01\
A)\x01B\x08\x01r\x02\x01xy\x01yy\x04\0\x04pair\x03\0\0\x01m\x03\x03red\x05green\x04\
blue\x04\0\x05color\x03\0\x02\x01q\x02\x04none\0\0\x04some\x01y\0\x04\0\x05maybe\
\x03\0\x04\x01n\x03\x04read\x05write\x04exec\x04\0\x05perms\x03\0\x06\x03\0\x0fd\
emo:test/types\x05\0\x02\x03\0\0\x04pair\x03\0\x04pair\x03\0\x01\x02\x03\0\0\x05\
color\x03\0\x05color\x03\0\x03\x02\x03\0\0\x05maybe\x03\0\x05maybe\x03\0\x05\x02\
\x03\0\0\x05perms\x03\0\x05perms\x03\0\x07\x01@\x02\x01ay\x01by\0y\x04\0\x03add\x01\
\x09\x01@\x02\x01az\x01bz\0z\x04\0\x03sub\x01\x0a\x01@\x02\x01av\x01bv\0v\x04\0\x05\
mul-f\x01\x0b\x01@\x02\x01au\x01bu\0u\x04\0\x05div-d\x01\x0c\x01@\x01\x04names\0\
s\x04\0\x05greet\x01\x0d\x01py\x01@\x01\x02xs\x0e\0y\x04\0\x08sum-list\x01\x0f\x01\
@\x01\x02xs\x0e\0\x0e\x04\0\x0bdouble-list\x01\x10\x01@\x02\x01ay\x01by\0\x02\x04\
\0\x09make-pair\x01\x11\x01@\x01\x01p\x02\0\x02\x04\0\x09swap-pair\x01\x12\x01j\x01\
y\x01s\x01@\x01\x04flag\x7f\0\x13\x04\0\x07try-get\x01\x14\x01ky\x01@\x02\x06cho\
ice\x04\x03valy\0\x15\x04\0\x04pick\x01\x16\x01@\x01\x01v\x06\0\x06\x04\0\x0aech\
o-maybe\x01\x17\x01@\x01\x01f\x08\0y\x04\0\x0bcount-flags\x01\x18\x01@\x01\x01b\x7f\
\0\x7f\x04\0\x08not-bool\x01\x19\x04\0\x0edemo:test/demo\x04\0\x0b\x0a\x01\0\x04\
demo\x03\0\0\0G\x09producers\x01\x0cprocessed-by\x02\x0dwit-component\x070.227.1\
\x10wit-bindgen-rust\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
