-- test_py_wasm.lua - 使用 Python 生成的 WASM
local wasmtime = require("wasmtime")
local f = io.open("test/py_wasm.wasm", "rb")
local bin = f:read("*all")
f:close()

print("size:", #bin)
print("validate:", wasmtime.validate(bin))
local engine = wasmtime.newEngine()
local module = wasmtime.newModule(engine, bin)
print("[OK] module")
local store = wasmtime.newStore(engine)
local inst = wasmtime.newInstance(store, module, {})
local f2 = inst:getExport("add")
print("add(5,7) =", f2:call(5, 7))