#ifndef lvmprotect_h
#define lvmprotect_h

#include <stddef.h>
#include <stdint.h>

/* ASM Prefix handling */
#if defined(__APPLE__)
#define ASM_GLOBAL ".globl"
#define ASM_PREFIX "_"
#elif defined(_WIN32) || defined(__CYGWIN__)
#define ASM_GLOBAL ".globl"
#if defined(__x86_64__) || defined(__aarch64__)
#define ASM_PREFIX ""
#else
#define ASM_PREFIX "_"
#endif
#else
#define ASM_GLOBAL ".global"
#define ASM_PREFIX ""
#endif

/* VMP Marker bytes */
#if defined(__x86_64__) || defined(_M_X64) || defined(__i386) || defined(_M_IX86)
#define VMP_BYTES ".byte 0x4C, 0x58, 0x43, 0x4C\n.byte 0x4C, 0x58, 0x43, 0x4C\n.byte 0x90, 0x90\n"
#else
#define VMP_BYTES ".byte 0x4C, 0x58, 0x43, 0x4C\n.byte 0x4C, 0x58, 0x43, 0x4C\n"
#endif

/* Macro to generate VMP markers */
#define VMP_MARKER(name) \
  __asm__( \
    ASM_GLOBAL " " ASM_PREFIX #name "_start\n" \
    ASM_PREFIX #name "_start:\n" \
    VMP_BYTES \
    ASM_GLOBAL " " ASM_PREFIX #name "_end\n" \
    ASM_PREFIX #name "_end:\n" \
  )

/* Declaration for the start and end symbols generated by VMP_MARKER */
#define DECLARE_VMP_MARKER(name) \
  extern char name##_start[]; \
  extern char name##_end[]

/* Memory patching function declaration */
void vmp_patch_memory(void* start, void* end, void* target_handler);

#endif
