#ifndef LXCLUA_CORE_H
#define LXCLUA_CORE_H
/*
 * lxclua_core.h -- aggregated include for ALL LXCLUA internal headers
 * Auto-generated by 'make gen-header'. DO NOT EDIT MANUALLY.
 * Include this single file when you need full internal access.
 * For the public embedding API only, use lxclua.h instead.
 */
#ifdef __cplusplus
extern "C" {
#endif

/* [10] Base configuration */
#include "src/core/luaconf.h"
#include "src/core/lprefix.h"

/* [20] Public Lua C API */
#include "src/core/lua.h"
#include "src/core/lauxlib.h"
#include "src/core/lualib.h"
#include "src/core/lmap.h"

/* [30] Core internals */
#include "src/core/lapi.h"
#include "src/core/lstate.h"
#include "src/core/llimits.h"
#include "src/core/lmem.h"
#include "src/core/lobject.h"
#include "src/core/lfunc.h"
#include "src/core/lzio.h"
#include "src/core/lstring.h"
#include "src/core/ltable.h"
#include "src/core/ltm.h"
#include "src/core/lgc.h"
#include "src/core/ldebug.h"
#include "src/core/ldo.h"
#include "src/core/lcode.h"
#include "src/core/lopcodes.h"
#include "src/core/lopnames.h"
#include "src/core/lundump.h"

/* [40] Standard library extensions */
#include "src/stdlib/lclass.h"
#include "src/stdlib/lstruct.h"
#include "src/stdlib/lsuper.h"

/* [50] Utility modules */
#include "src/utils/aes.h"
#include "src/utils/crc.h"
#include "src/utils/csprng.h"
#include "src/utils/json_parser.h"
#include "src/utils/laio.h"
#include "src/utils/lbigint.h"
#include "src/utils/lctype.h"
#include "src/utils/leventloop.h"
#include "src/utils/lnamespace.h"
#include "src/utils/lpromise.h"
#include "src/utils/lthread.h"
#include "src/utils/ltranslator.h"
#include "src/utils/sha256.h"
#include "src/utils/unidata.h"

/* [55] Utility with BasicBlock rename (conflicts with llexer_compiler.h) */
#pragma push_macro("BasicBlock")
#define BasicBlock LObfuscateBasicBlock
#include "src/utils/lobfuscate.h"
#pragma pop_macro("BasicBlock")

/* [60] Compiler / AST / Bytecode / LBCTC */
#include "src/compiler/lasm.h"
#include "src/compiler/last.h"
#include "src/compiler/last_parse.h"
#include "src/compiler/last_serialize.h"
#include "src/compiler/last_unparse.h"
#include "src/compiler/last_visitor.h"
#include "src/compiler/lbctc.h"
#include "src/compiler/lcodegen.h"
#include "src/compiler/llex.h"
#pragma push_macro("BasicBlock")
#define BasicBlock LLexerBasicBlock
#include "src/compiler/llexer_compiler.h"
#pragma pop_macro("BasicBlock")
#include "src/compiler/lparser.h"

/* [70] VM core */
#include "src/vm/lvm.h"

/* [99] Special headers (cannot be directly included, listed for reference) */
/* special: src/compiler/lbctc_api_list.h -- X-macro list: requires external X() macro context */
/* special: src/lspsrv/lspsrv.h -- LSP server has its own duplicate AST enum/struct definitions (conflicts with last.h) */
/* special: src/vm/ljumptab.h -- computed goto label table: only valid inside lvm.c function scope */

#ifdef __cplusplus
}
#endif
#endif /* LXCLUA_CORE_H */
