#ifndef LXCLUA_H
#define LXCLUA_H
/* LXCLUA Aggregated Header - auto-generated by make gen-header - do not edit manually */
#ifdef __cplusplus
extern "C" {
#endif

/* 第一组：基础配置 */
#include "src/core/luaconf.h"
#include "src/core/lprefix.h"

/* 第二组：公开API（核心Lua） */
#include "src/core/lua.h"
#include "src/core/lauxlib.h"
#include "src/core/lualib.h"

/* 第三组：核心内部头（按依赖顺序） */
#include "src/core/lapi.h"
#include "src/core/lstate.h"
#include "src/core/llimits.h"
#include "src/core/lmem.h"
#include "src/core/lobject.h"
#include "src/core/lfunc.h"
#include "src/core/lzio.h"
#include "src/core/lstring.h"
#include "src/core/ltable.h"
#include "src/core/ltm.h"
#include "src/core/lgc.h"
#include "src/core/ldebug.h"
#include "src/core/ldo.h"
#include "src/core/lcode.h"
#include "src/core/lopcodes.h"
#include "src/core/lopnames.h"
#include "src/core/lundump.h"
#include "src/core/lmap.h"

/* 第四组：LXCLUA 核心扩展 */
#include "src/utils/lctype.h"
#include "src/stdlib/lclass.h"
#include "src/stdlib/lstruct.h"
#include "src/stdlib/lsuper.h"
#include "src/utils/lnamespace.h"
#include "src/utils/lbigint.h"
#include "src/utils/lthread.h"
#include "src/utils/lpromise.h"
#include "src/utils/leventloop.h"
#include "src/utils/laio.h"
#include "src/utils/ltranslator.h"

/* lobfuscate.h: 重命名 BasicBlock 避免与 llexer_compiler.h 冲突 */
#define BasicBlock LObfuscateBasicBlock
#include "src/utils/lobfuscate.h"
#undef BasicBlock
#include "src/utils/sha256.h"
#include "src/utils/aes.h"
#include "src/utils/crc.h"
#include "src/utils/csprng.h"

/* 第五组：编译器/汇编器 */
#include "src/compiler/lbctc.h"
#include "src/compiler/lasm.h"
#include "src/compiler/last.h"
#include "src/compiler/last_parse.h"
#include "src/compiler/last_serialize.h"
#include "src/compiler/last_unparse.h"
#include "src/compiler/last_visitor.h"
#include "src/compiler/lcodegen.h"
#include "src/compiler/llex.h"
#include "src/compiler/lparser.h"

/* llexer_compiler.h: 重命名 BasicBlock 避免与 lobfuscate.h 冲突 */
#define BasicBlock LLexerBasicBlock
#include "src/compiler/llexer_compiler.h"
#undef BasicBlock
/* lbctc_api_list.h omitted (X-macro context required) */

/* 第六组：VM（F2Imod 类型定义在 lvm.h，必须放在 JIT 之前） */
#include "src/vm/lvm.h"
/* ljumptab.h omitted (VM internal goto table) */

/* 第八组：其他通用工具 */
#include "src/utils/json_parser.h"
#include "src/utils/unidata.h"

#ifdef __cplusplus
}
#endif
#endif /* LXCLUA_H */
