-- 简化测试: 只有FORLOOP+STATE_ENCODE
local code = "local sum = 0; for i = 1, 10 do sum = sum + i; end; return sum"
local fn = load(code)

local flags = 1 | 8  -- CFF + STATE_ENCODE (no RANDOM_NOP)
local obf_dump = string.dump(fn, {
    obfuscate = flags, seed = 12345, strip = false
})
local obf_fn = load(obf_dump)
local ok, res = pcall(obf_fn)
print("CFF+STATE_ENCODE for-loop: " .. (ok and tostring(res) or "ERROR: " .. tostring(res)))

-- Now with RANDOM_NOP alone
fn = load(code)
flags = 1 | 512  -- CFF + RANDOM_NOP
obf_dump = string.dump(fn, {
    obfuscate = flags, seed = 12345, strip = false
})
obf_fn = load(obf_dump)
ok, res = pcall(obf_fn)
print("CFF+RANDOM_NOP for-loop: " .. (ok and tostring(res) or "ERROR: " .. tostring(res)))

-- Now with both
fn = load(code)
flags = 1 | 512 | 8  -- CFF + RANDOM_NOP + STATE_ENCODE
obf_dump = string.dump(fn, {
    obfuscate = flags, seed = 12345, strip = false
})
print("Generated bytecode length: " .. #obf_dump)
obf_fn = load(obf_dump)
ok, res = pcall(obf_fn)
print("CFF+RANDOM_NOP+STATE_ENCODE for-loop: " .. (ok and tostring(res) or "ERROR: " .. tostring(res)))
