-- covers: OP_MOVE,OP_LOADI,OP_LOADF,OP_LOADK,OP_ADDI,OP_ADDK,OP_SUBK,OP_MULK,OP_MODK,OP_POWK,OP_DIVK,OP_IDIVK,OP_BANDK,OP_BORK,OP_BXORK,OP_SHLI,OP_SHRI,OP_ADD,OP_SUB,OP_MUL,OP_MOD,OP_POW,OP_DIV,OP_IDIV,OP_BAND,OP_BOR,OP_BXOR,OP_SHL,OP_SHR,OP_UNM,OP_BNOT,OP_NOT,OP_EQ,OP_LT,OP_LE,OP_EQI,OP_LTI,OP_LEI,OP_GTI,OP_GEI
print("=== 001 basic_arith START ===")
print("add_1_2: " .. tostring(1 + 2))
print("sub_5_3: " .. tostring(5 - 3))
print("mul_4_3: " .. tostring(4 * 3))
print("div_15_4: " .. string.format("%.10g", 15 / 4))
print("mod_15_4: " .. tostring(15 % 4))
print("idiv_15_4: " .. tostring(15 // 4))
print("pow_2_10: " .. tostring(2 ^ 10))
print("band_FF_0F: " .. tostring(0xFF & 0x0F))
print("bor_F0_0F: " .. tostring(0xF0 | 0x0F))
print("bxor_FF_0F: " .. tostring(0xFF ~ 0x0F))
print("shl_1_8: " .. tostring(1 << 8))
print("shr_256_3: " .. tostring(256 >> 3))
print("unm_minus5: " .. tostring(-5))
print("bnot_0: " .. tostring(~0))
print("lt_1_2: " .. (1 < 2 and 1 or 0))
print("le_2_2: " .. (2 <= 2 and 1 or 0))
print("gt_5_3: " .. (5 > 3 and 1 or 0))
print("ge_5_5: " .. (5 >= 5 and 1 or 0))
print("eq_2_2: " .. (2 == 2 and 1 or 0))
print("neq_2_3: " .. (2 ~= 3 and 1 or 0))
local sa = 1 and 2
print("short_and_1_2: " .. tostring(sa))
local so = nil or 42
print("short_or_nil_42: " .. tostring(so))
print("=== 001 basic_arith END ===")
